"""
Constants for UBL conversion.

Central location for all constant definitions used across the codebase.
"""

# Map UBL numeric type codes to document type strings
# Per UBL 2.1 spec - UNCL 1001 Invoice Type Code
NUMERIC_TYPE_TO_DOCUMENT_TYPE = {
    "1": "Catalogue",
    "10": "ContractNotice",
    "11": "PriorInformationNotice",
    "129": "CatalogueRequest",
    "140": "Forecast",
    "141": "ForecastRevision",
    "142": "InventoryReport",
    "143": "ProductActivity",
    "144": "RetailEvent",
    "145": "StockAvailabilityReport",
    "146": "TradeItemLocationProfile",
    "147": "TransportProgressStatus",
    "148": "TransportProgressStatusRequest",
    "149": "TransportServiceDescription",
    "15": "ContractAwardNotice",
    "150": "TransportServiceDescriptionRequest",
    "17": "CallForTenders",
    "170": "CataloguePricingUpdate",
    "171": "CatalogueItemSpecificationUpdate",
    "172": "CatalogueDeletion",
    "21": "ItemInformationRequest",
    "220": "Order",
    "221": "OrderResponseSimple",
    "227": "OrderChange",
    "230": "OrderCancellation",
    "231": "OrderResponse",
    "232": "FulfilmentCancellation",
    "24": "AwardedNotification",
    "25": "UnawardedNotification",
    "271": "PackingList",
    "310": "RequestForQuotation",
    "311": "ApplicationResponse",
    "312": "DocumentStatus",
    "313": "DocumentStatusRequest",
    "315": "Quotation",
    "325": "Statement",
    "326": "UtilityStatement",
    "380": "Invoice",
    "381": "CreditNote",
    "383": "DebitNote",
    "389": "SelfBilledInvoice",
    "396": "SelfBilledCreditNote",
    "42": "TransportationStatus",
    "43": "TransportationStatusRequest",
    "430": "RemittanceAdvice",
    "447": "GuaranteeCertificate",
    "45": "TenderReceipt",
    "50": "Tender",
    "54": "TendererQualification",
    "55": "TendererQualificationResponse",
    "6": "CertificateOfOrigin",
    "610": "ForwardingInstructions",
    "632": "DespatchAdvice",
    "633": "ReceiptAdvice",
    "635": "InstructionForReturns",
    "705": "BillOfLading",
    "71": "Reminder",
    "716": "Waybill",
    "744": "GoodsItemItinerary",
    "76": "TransportExecutionPlanRequest",
    "77": "TransportExecutionPlan",
    "780": "FreightInvoice",
    "916": "AttachedDocument",
    "92": "ExceptionCriteria",
    "93": "ExceptionNotification",
}
